create type "public"."container_status" as enum ('solicitado', 'despachado', 'en_RFE', 'nacionalizado');

create table "public"."containers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "container_number" character varying not null,
    "status" container_status not null,
    "current_location" location not null,
    "requested_date" date not null,
    "dispatched_date" date,
    "rfe_arrival_date" date,
    "nationalization_date" date,
    "last_updated" timestamp without time zone not null default now(),
    "notes" text
);


alter table "public"."containers" enable row level security;

create table "public"."containers_products" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "container_id" bigint not null,
    "product_id" bigint not null,
    "quantity" smallint not null,
    "last_updated" timestamp without time zone not null default now()
);


alter table "public"."containers_products" enable row level security;

create table "public"."document" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "container_id" bigint not null,
    "document_type_id" bigint,
    "document_url" text not null
);


alter table "public"."document" enable row level security;

create table "public"."document_type" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
);


alter table "public"."document_type" enable row level security;

alter table "public"."inventory" add column "last_updated" timestamp without time zone not null default now();

alter table "public"."products" add column "last_updated" timestamp without time zone not null default now();

CREATE UNIQUE INDEX containers_container_number_key ON public.containers USING btree (container_number);

CREATE UNIQUE INDEX containers_pkey ON public.containers USING btree (id);

CREATE UNIQUE INDEX containers_products_pkey ON public.containers_products USING btree (id);

CREATE UNIQUE INDEX document_pkey ON public.document USING btree (id);

CREATE UNIQUE INDEX document_type_pkey ON public.document_type USING btree (id);

alter table "public"."containers" add constraint "containers_pkey" PRIMARY KEY using index "containers_pkey";

alter table "public"."containers_products" add constraint "containers_products_pkey" PRIMARY KEY using index "containers_products_pkey";

alter table "public"."document" add constraint "document_pkey" PRIMARY KEY using index "document_pkey";

alter table "public"."document_type" add constraint "document_type_pkey" PRIMARY KEY using index "document_type_pkey";

alter table "public"."containers" add constraint "containers_container_number_key" UNIQUE using index "containers_container_number_key";

alter table "public"."containers_products" add constraint "containers_products_container_id_fkey" FOREIGN KEY (container_id) REFERENCES containers(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."containers_products" validate constraint "containers_products_container_id_fkey";

alter table "public"."containers_products" add constraint "containers_products_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."containers_products" validate constraint "containers_products_product_id_fkey";

alter table "public"."document" add constraint "document_container_id_fkey" FOREIGN KEY (container_id) REFERENCES containers(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."document" validate constraint "document_container_id_fkey";

alter table "public"."document" add constraint "document_document_type_id_fkey" FOREIGN KEY (document_type_id) REFERENCES document_type(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."document" validate constraint "document_document_type_id_fkey";

grant delete on table "public"."containers" to "anon";

grant insert on table "public"."containers" to "anon";

grant references on table "public"."containers" to "anon";

grant select on table "public"."containers" to "anon";

grant trigger on table "public"."containers" to "anon";

grant truncate on table "public"."containers" to "anon";

grant update on table "public"."containers" to "anon";

grant delete on table "public"."containers" to "authenticated";

grant insert on table "public"."containers" to "authenticated";

grant references on table "public"."containers" to "authenticated";

grant select on table "public"."containers" to "authenticated";

grant trigger on table "public"."containers" to "authenticated";

grant truncate on table "public"."containers" to "authenticated";

grant update on table "public"."containers" to "authenticated";

grant delete on table "public"."containers" to "service_role";

grant insert on table "public"."containers" to "service_role";

grant references on table "public"."containers" to "service_role";

grant select on table "public"."containers" to "service_role";

grant trigger on table "public"."containers" to "service_role";

grant truncate on table "public"."containers" to "service_role";

grant update on table "public"."containers" to "service_role";

grant delete on table "public"."containers_products" to "anon";

grant insert on table "public"."containers_products" to "anon";

grant references on table "public"."containers_products" to "anon";

grant select on table "public"."containers_products" to "anon";

grant trigger on table "public"."containers_products" to "anon";

grant truncate on table "public"."containers_products" to "anon";

grant update on table "public"."containers_products" to "anon";

grant delete on table "public"."containers_products" to "authenticated";

grant insert on table "public"."containers_products" to "authenticated";

grant references on table "public"."containers_products" to "authenticated";

grant select on table "public"."containers_products" to "authenticated";

grant trigger on table "public"."containers_products" to "authenticated";

grant truncate on table "public"."containers_products" to "authenticated";

grant update on table "public"."containers_products" to "authenticated";

grant delete on table "public"."containers_products" to "service_role";

grant insert on table "public"."containers_products" to "service_role";

grant references on table "public"."containers_products" to "service_role";

grant select on table "public"."containers_products" to "service_role";

grant trigger on table "public"."containers_products" to "service_role";

grant truncate on table "public"."containers_products" to "service_role";

grant update on table "public"."containers_products" to "service_role";

grant delete on table "public"."document" to "anon";

grant insert on table "public"."document" to "anon";

grant references on table "public"."document" to "anon";

grant select on table "public"."document" to "anon";

grant trigger on table "public"."document" to "anon";

grant truncate on table "public"."document" to "anon";

grant update on table "public"."document" to "anon";

grant delete on table "public"."document" to "authenticated";

grant insert on table "public"."document" to "authenticated";

grant references on table "public"."document" to "authenticated";

grant select on table "public"."document" to "authenticated";

grant trigger on table "public"."document" to "authenticated";

grant truncate on table "public"."document" to "authenticated";

grant update on table "public"."document" to "authenticated";

grant delete on table "public"."document" to "service_role";

grant insert on table "public"."document" to "service_role";

grant references on table "public"."document" to "service_role";

grant select on table "public"."document" to "service_role";

grant trigger on table "public"."document" to "service_role";

grant truncate on table "public"."document" to "service_role";

grant update on table "public"."document" to "service_role";

grant delete on table "public"."document_type" to "anon";

grant insert on table "public"."document_type" to "anon";

grant references on table "public"."document_type" to "anon";

grant select on table "public"."document_type" to "anon";

grant trigger on table "public"."document_type" to "anon";

grant truncate on table "public"."document_type" to "anon";

grant update on table "public"."document_type" to "anon";

grant delete on table "public"."document_type" to "authenticated";

grant insert on table "public"."document_type" to "authenticated";

grant references on table "public"."document_type" to "authenticated";

grant select on table "public"."document_type" to "authenticated";

grant trigger on table "public"."document_type" to "authenticated";

grant truncate on table "public"."document_type" to "authenticated";

grant update on table "public"."document_type" to "authenticated";

grant delete on table "public"."document_type" to "service_role";

grant insert on table "public"."document_type" to "service_role";

grant references on table "public"."document_type" to "service_role";

grant select on table "public"."document_type" to "service_role";

grant trigger on table "public"."document_type" to "service_role";

grant truncate on table "public"."document_type" to "service_role";

grant update on table "public"."document_type" to "service_role";


