create type "public"."location" as enum ('En_Camino', 'RFE', 'Almacen_Nacional', 'Deposito_Fiscal');

create table "public"."importers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "contact_info" jsonb
);


alter table "public"."importers" enable row level security;

create table "public"."inventory" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "product_id" bigint not null,
    "location" location not null,
    "nationalized" boolean not null,
    "quantity" bigint not null
);


alter table "public"."inventory" enable row level security;

create table "public"."products" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "description" text,
    "importer_id" bigint not null,
    "sku" text not null,
    "unit_price" numeric
);


alter table "public"."products" enable row level security;

CREATE UNIQUE INDEX importers_name_key ON public.importers USING btree (name);

CREATE UNIQUE INDEX importers_pkey ON public.importers USING btree (id);

CREATE UNIQUE INDEX inventory_pkey ON public.inventory USING btree (id);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

CREATE UNIQUE INDEX products_sku_key ON public.products USING btree (sku);

alter table "public"."importers" add constraint "importers_pkey" PRIMARY KEY using index "importers_pkey";

alter table "public"."inventory" add constraint "inventory_pkey" PRIMARY KEY using index "inventory_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."importers" add constraint "importers_name_key" UNIQUE using index "importers_name_key";

alter table "public"."inventory" add constraint "inventory_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."inventory" validate constraint "inventory_product_id_fkey";

alter table "public"."products" add constraint "products_importer_id_fkey" FOREIGN KEY (importer_id) REFERENCES importers(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."products" validate constraint "products_importer_id_fkey";

alter table "public"."products" add constraint "products_sku_key" UNIQUE using index "products_sku_key";

grant delete on table "public"."importers" to "anon";

grant insert on table "public"."importers" to "anon";

grant references on table "public"."importers" to "anon";

grant select on table "public"."importers" to "anon";

grant trigger on table "public"."importers" to "anon";

grant truncate on table "public"."importers" to "anon";

grant update on table "public"."importers" to "anon";

grant delete on table "public"."importers" to "authenticated";

grant insert on table "public"."importers" to "authenticated";

grant references on table "public"."importers" to "authenticated";

grant select on table "public"."importers" to "authenticated";

grant trigger on table "public"."importers" to "authenticated";

grant truncate on table "public"."importers" to "authenticated";

grant update on table "public"."importers" to "authenticated";

grant delete on table "public"."importers" to "service_role";

grant insert on table "public"."importers" to "service_role";

grant references on table "public"."importers" to "service_role";

grant select on table "public"."importers" to "service_role";

grant trigger on table "public"."importers" to "service_role";

grant truncate on table "public"."importers" to "service_role";

grant update on table "public"."importers" to "service_role";

grant delete on table "public"."inventory" to "anon";

grant insert on table "public"."inventory" to "anon";

grant references on table "public"."inventory" to "anon";

grant select on table "public"."inventory" to "anon";

grant trigger on table "public"."inventory" to "anon";

grant truncate on table "public"."inventory" to "anon";

grant update on table "public"."inventory" to "anon";

grant delete on table "public"."inventory" to "authenticated";

grant insert on table "public"."inventory" to "authenticated";

grant references on table "public"."inventory" to "authenticated";

grant select on table "public"."inventory" to "authenticated";

grant trigger on table "public"."inventory" to "authenticated";

grant truncate on table "public"."inventory" to "authenticated";

grant update on table "public"."inventory" to "authenticated";

grant delete on table "public"."inventory" to "service_role";

grant insert on table "public"."inventory" to "service_role";

grant references on table "public"."inventory" to "service_role";

grant select on table "public"."inventory" to "service_role";

grant trigger on table "public"."inventory" to "service_role";

grant truncate on table "public"."inventory" to "service_role";

grant update on table "public"."inventory" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";


